dotnet build src\FoodTruckSearchApp\FoodTruckSearchBackendAPI\FoodTruckSearchBackendAPI.csproj

dotnet run --project src\FoodTruckSearchApp\FoodTruckSearchFrontEnd\FoodTruckSearchFrontEnd.csproj --IISExpress