name: Docker Image CI

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

jobs:

  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v2
    - name: Build the Docker image - FrontEnd
      run: docker build . --file src/FoodTruckSearchApp/FoodTruckSearchFrontEnd/Dockerfile --tag food-truck-search-frontend:$(date +%s)

    - name: Build the Docker image - Backend
      run: docker build . --file src/FoodTruckSearchApp/FoodTruckSearchBackendAPI/Dockerfile --tag food-truck-search-backend:$(date +%s)
